/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ir_gui;
import invertedIndex.*;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import postional.*;
import static postional.PositionVersion2.readDoc;

/**
 *
 * @author Ansam
 */

public class file_choose extends javax.swing.JFrame {

    /**
     * Creates new form file_choose
     */
    Task2 T;
    int i;
    int taskno;
    public ArrayList<File> files;
    int filesno;
    PositionVersion2 pos;

    public file_choose(Task2 T,int i,int taskno,ArrayList<File> files,int filesno,PositionVersion2 pos) {
        initComponents();
        this.T=T;
        this.i=i;
        this.taskno=taskno;
        this.filesno=filesno;
        this.files=files;
        jLabel2.setText("DOC "+(i+1));
        this.pos=pos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel2.setText("DOC 1:");

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path=jFileChooser1.getSelectedFile().getPath();
            File filename=jFileChooser1.getSelectedFile();
            files.add(filename);
            System.out.print(path);
        if(this.taskno==2)//inverted
        {
            try {
                T.ReadDoc(path, i);
            } catch (IOException ex) {
                Logger.getLogger(file_choose.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
             

            if(i==filesno)
            {
                T.AfterRead();
             new Table_matrix(T,2,null,null,null,files,null,0).setVisible(true);
            }
            else{
            new file_choose(T,i,2,files,4,null).setVisible(true);
             this.setVisible(false);}
                
        }
        if(this.taskno==3)
        {
            pos.readDoc(path);
             i++;
            
             if(i==filesno)
            {
                new query(null, taskno, null, files,pos).setVisible(true);
               this.setVisible(false); 
            }
             else{
              new file_choose(T,i,taskno,files,filesno,pos).setVisible(true);
             this.setVisible(false);}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
