/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ir_gui;

import Boolean.*;
import invertedIndex.*;
import java.io.File;
import static java.lang.reflect.Array.set;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import postional.PositionVersion2;

/**
 *
 * @author Ansam
 */
public class query extends javax.swing.JFrame {

    /**
     * Creates new form Boolean_query
     */
    Task2 T;
    int taskno;
    SimpleQuery q ;
    Query2 CQ;
    table2 t;
    ArrayList<File> files;
    PositionVersion2 pos;

    ArrayList<ArrayList<Integer>> termVectors=new ArrayList<ArrayList<Integer>>() ;
    public query(Task2 T,int taskno,table2 t,ArrayList<File> files,PositionVersion2 pos) {
        initComponents();
        this.T=T;
        this.taskno=taskno;
        this.t=t;
        this.files=files;
        this.pos=pos;
        if(taskno==2)
            jButton2.setVisible(false);
        if(taskno==3)
            jButton2.setVisible(false);


            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel1.setText("Query");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Complex Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(taskno==2)
        {
        Output2 Query = new Output2(T);
        Query.QueryEdits(jTextArea1.getText());
        new Matched_Doc(Query,2,null,files,T,null,t).setVisible(true);
        this.setVisible(false);
        }
         if(taskno==1)
        {
            q = new SimpleQuery();
            String query=jTextArea1.getText();
            ArrayList<String> ff=new ArrayList<>();
        String[] termsCollection = query.split(" ");
        for(int i=0;i<termsCollection.length;i++)
        {    
            ff.add(termsCollection[i]);
        }
         Set<String> tokens=new HashSet<>(ff);
             new Table_matrix(null,1,t,tokens,q.brackets(ff),null,null,1).setVisible(true);
             this.setVisible(false);

        }
         if(taskno==3)
         {
            String query=jTextArea1.getText();
             pos.GetQuery(query);
             new Table_matrix(null,3,null,null,null,files,pos,0).setVisible(true);
             this.setVisible(false);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CQ = new Query2();
            String query=jTextArea1.getText();
            ArrayList<String> ff=new ArrayList<>();
        String[] termsCollection = query.split(" ");
        for(int i=0;i<termsCollection.length;i++)
        {    
            ff.add(termsCollection[i]);
        }
            Set<String> tokens=new HashSet<>(ff);
             new Table_matrix(null,1,t,tokens,CQ.brackets(ff),null,null,2).setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
